MNT Use GitHub Actions CI
silverstripe/cwp-search pull request #44
Opened 2022-07-05 05:26 UTC by emteknetnz

Issue https://github.com/silverstripe/gha-ci/issues/11<br /><br />Workflow run https://github.com/creative-commoners/cwp-search/actions?query=branch%3Apulls%2F1.6%2Fmodule-standards

2022-07-14 22:23 UTC, GuySartorelli requested changes

2022-07-14 22:23 UTC, GuySartorelli commented on composer.json
> +        "tractorcow/classproxy": "<0.1.2"
Why this conflict?

2022-07-14 23:21 UTC, emteknetnz commented on composer.json
> +        "tractorcow/classproxy": "<0.1.2"
Removed, did not fix issue

2022-07-15 00:18 UTC, GuySartorelli approved these changes

2022-07-15 00:18 UTC, merged